import { defineConfig } from 'vite';
import handlebars from 'vite-plugin-handlebars';
import path from 'path';
import fs from 'fs';
import sharp from 'sharp';
import tailwindcss from '@tailwindcss/vite';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Определяем объект input для Rollup
const rollupInputs = {
  Главная: path.resolve(__dirname, 'src/html/index.html'),
  ui_kit: path.resolve(__dirname, 'src/html/ui-kit.html'),
  error: path.resolve(__dirname, 'src/html/404.html'),
};

// Функция для экспорта в JS файл (ВЫЗЫВАЕМ СРАЗУ)
function exportInputsToFile() {
  try {
    const exportPath = path.resolve(__dirname, 'src/js/libs/rollup-inputs.js');
    
    // Создаем директорию, если она не существует
    const exportDir = path.dirname(exportPath);
    if (!fs.existsSync(exportDir)) {
      fs.mkdirSync(exportDir, { recursive: true });
    }

    // Создаем объект с относительными путями для удобства использования
    const relativePaths = Object.fromEntries(
      Object.entries(rollupInputs).map(([key, absolutePath]) => [
        key, 
        path.relative(path.resolve(__dirname, 'src'), absolutePath)
      ])
    );

    const content = `// Auto-generated from vite.config.js
// Generated on: ${new Date().toISOString()}
// DO NOT EDIT THIS FILE MANUALLY

/**
 * Rollup input configuration for Vite build
 * Contains absolute paths to HTML entry points
 */
export const rollupInputs = ${JSON.stringify(rollupInputs, null, 2)};

/**
 * Relative paths from src directory
 * Useful for navigation within the project
 */
export const relativePaths = ${JSON.stringify(relativePaths, null, 2)};

/**
 * List of available page keys
 */
export const pageKeys = ${JSON.stringify(Object.keys(rollupInputs), null, 2)};

/**
 * Get the path for a specific page
 * @param {string} pageKey - Key of the page (index, ui_kit, error, etc.)
 * @returns {string|null} Absolute path or null if not found
 */
export function getPagePath(pageKey) {
  return rollupInputs[pageKey] || null;
}

/**
 * Get the relative path for a specific page
 * @param {string} pageKey - Key of the page (index, ui_kit, error, etc.)
 * @returns {string|null} Relative path from src directory or null if not found
 */
export function getPageRelativePath(pageKey) {
  return relativePaths[pageKey] || null;
}

/**
 * Check if a page key exists
 * @param {string} pageKey - Key to check
 * @returns {boolean} True if the page exists
 */
export function hasPage(pageKey) {
  return pageKey in rollupInputs;
}

export default rollupInputs;
`;

    fs.writeFileSync(exportPath, content);
    console.log('📁 Rollup inputs exported to: src/js/libs/rollup-inputs.js');
    console.log('📋 Available pages:', Object.keys(rollupInputs));
    
  } catch (error) {
    console.error('❌ Error exporting rollup inputs:', error);
  }
}

// ВЫЗЫВАЕМ ФУНКЦИЮ ЭКСПОРТА СРАЗУ ЖЕ
exportInputsToFile();

// Хелпер для определения веса шрифта
function getFontWeight(style) {
  const weights = {
    'thin': 100,
    'extralight': 200,
    'light': 300,
    'regular': 400,
    'normal': 400,
    'medium': 500,
    'semibold': 600,
    'bold': 700,
    'extrabold': 800,
    'black': 900
  };
  
  return weights[style.toLowerCase()] || 400;
}

// Хелпер для определения формата
function getFormat(ext) {
  const formats = {
    'woff2': 'woff2',
    'woff': 'woff',
    'ttf': 'truetype',
    'otf': 'opentype'
  };
  
  return formats[ext] || ext;
}

// ✅ ПРОСТОЙ ПЛАГИН ДЛЯ ЗАМЕНЫ CSS ССЫЛКИ
const simpleAsyncCSSPlugin = () => {
  return {
    name: 'simple-async-css',
    apply: 'build',
    
    transformIndexHtml(html) {
      console.log('🎯 Making CSS async...');
      
      // Простая замена синхронной загрузки на асинхронную
      return html.replace(
        /<link rel="stylesheet"[^>]*?href="([^"]*?main[^"]*?\.css)"[^>]*?>/i,
        `<!-- CSS loaded asynchronously -->
<link rel="preload" href="$1" as="style" onload="this.onload=null;this.rel='stylesheet'">
<noscript><link rel="stylesheet" href="$1"></noscript>
<script>
  // Fallback for async CSS loading
  document.addEventListener('DOMContentLoaded', function() {
    var link = document.createElement('link');
    link.rel = 'stylesheet';
    link.href = '$1';
    document.head.appendChild(link);
  });
</script>`
      );
    }
  };
};

// ✅ ФУНКЦИЯ ДЛЯ ИЗВЛЕЧЕНИЯ CRITICAL CSS (ВЫНЕСЕНА ОТДЕЛЬНО)
function extractCriticalCSS(fullCSS) {
  // Базовые критические стили
  let criticalCSS = `/* Critical CSS - Above The Fold Content */
/* Generated automatically during build */

/* Reset and base styles */
* { box-sizing: border-box; }
html { scroll-behavior: smooth; }
body { 
  margin: 0; 
  font-family: system-ui, -apple-system, sans-serif;
  line-height: 1.5;
}

/* Critical layout components */
header, nav, .header, .navigation, 
.hero, .banner, .first-screen,
h1, h2, h3, .title, .subtitle {
  /* Ensure critical elements are styled */
}

/* Critical typography */
h1, h2, h3, h4, h5, h6 {
  margin-top: 0;
  margin-bottom: 0.5em;
  line-height: 1.2;
}

/* Critical images */
img { max-width: 100%; height: auto; }

/* Critical buttons and links */
a { color: inherit; text-decoration: none; }
button { cursor: pointer; }

/* Loading states */
.critical-loading { opacity: 0; }
.critical-loaded { opacity: 1; transition: opacity 0.3s ease; }
`;

  // Извлекаем критические стили из основного CSS
  const criticalPatterns = [
    // Глобальные стили
    /(\*\{[^}]*\})/g,
    /(html[^{]*\{[^}]*\})/g,
    /(body[^{]*\{[^}]*\})/g,
    
    // Шрифты
    /(@font-face[^{]*\{[^}]*\})/g,
    
    // Критические селекторы
    /(\.(header|nav|hero|banner|first-screen|logo)[^{]*\{[^}]*\})/g,
    /(\.(btn|button|primary|main)[^{]*\{[^}]*\})/g,
    /(\.(title|heading|h[1-6])[^{]*\{[^}]*\})/g,
    
    // Медиа-запросы для мобильных
    /(@media[^{]*\{[^}]{1,500}\})/g
  ];

  criticalPatterns.forEach(pattern => {
    const matches = fullCSS.match(pattern);
    if (matches) {
      matches.forEach(match => {
        if (match.length < 800) { // Ограничиваем длину критических правил
          criticalCSS += '\n' + match + '\n';
        }
      });
    }
  });

  return criticalCSS;
}

// ✅ ПЛАГИН ДЛЯ АВТОМАТИЧЕСКОГО СОЗДАНИЯ CRITICAL CSS И ОТЛОЖЕННОЙ ЗАГРУЗКИ
const criticalCSSPlugin = () => {
  let isProduction = false;
  
  return {
    name: 'critical-css-plugin',
    
    config(config, { command }) {
      isProduction = command === 'build';
    },
    
    transformIndexHtml(html) {
      if (!isProduction) return html;
      
      console.log('🎯 Injecting critical CSS optimization...');
      
      // Создаем оптимизированную структуру для загрузки CSS
      const optimizedHTML = html
        .replace(
          /<link rel="stylesheet" href="(.*?main.*?\.css)">/g,
          `<!-- Critical CSS Optimization -->
<style>
/* Critical CSS will be inlined during build process */
/* Base critical styles for above-the-fold content */
.critical-hidden { opacity: 0; }
.critical-visible { opacity: 1; transition: opacity 0.3s ease-in-out; }
</style>

<!-- Preload critical resources -->
<link rel="preload" href="$1" as="style" onload="this.onload=null;this.rel='stylesheet'">
<noscript><link rel="stylesheet" href="$1"></noscript>

<!-- Load non-critical CSS with smart delay -->
<script>
(function() {
  var loadDeferredStyles = function() {
    var addStylesNode = document.getElementById('deferred-styles');
    var replacement = document.createElement('div');
    replacement.innerHTML = addStylesNode.textContent;
    document.body.appendChild(replacement);
    addStylesNode.parentElement.removeChild(addStylesNode);
  };
  
  var raf = requestAnimationFrame || mozRequestAnimationFrame ||
      webkitRequestAnimationFrame || msRequestAnimationFrame;
  if (raf) raf(function() { window.setTimeout(loadDeferredStyles, 0); });
  else window.addEventListener('load', loadDeferredStyles);
})();
</script>

<div id="deferred-styles">
  <link rel="stylesheet" href="$1" media="print" onload="this.media='all'">
</div>`
        )
        .replace(
          /<\/head>/,
          `<!-- CSS Loading State Handler -->
<script>
document.addEventListener('DOMContentLoaded', function() {
  // Mark critical content as visible
  setTimeout(function() {
    document.body.classList.add('critical-visible');
  }, 50);
  
  // Load full CSS after critical render
  var fullCSS = document.createElement('link');
  fullCSS.rel = 'stylesheet';
  fullCSS.href = '$1';
  fullCSS.onload = function() {
    document.body.classList.add('full-css-loaded');
    // Initialize components that depend on full CSS
    if (typeof window.initLazyComponents === 'function') {
      window.initLazyComponents();
    }
  };
  
  // Load full CSS with smart delay
  setTimeout(function() {
    document.head.appendChild(fullCSS);
  }, 200);
});
</script>
</head>`
        );

      return optimizedHTML;
    },
    
    async generateBundle(options, bundle) {
      if (!isProduction) return;
      
      console.log('🔧 Processing CSS for critical optimization...');
      
      // Находим все CSS файлы
      const cssFiles = Object.keys(bundle).filter(key => key.endsWith('.css'));
      
      for (const cssFile of cssFiles) {
        const cssAsset = bundle[cssFile];
        const cssContent = cssAsset.source;
        
        // Создаем упрощенную версию CSS для критических стилей
        if (cssFile.includes('main') || cssFile.includes('index')) {
          const criticalCSS = extractCriticalCSS(cssContent);
          
          // Сохраняем критический CSS как отдельный asset
          const criticalFileName = cssFile.replace('.css', '-critical.css');
          this.emitFile({
            type: 'asset',
            fileName: criticalFileName,
            source: criticalCSS
          });
          
          console.log(`✅ Generated critical CSS: ${criticalFileName}`);
        }
      }
    }
  };
};

// Улучшенный плагин для копирования dist в docs с исправлением HTML
const copyDistToDocs = () => {
  return {
    name: 'copy-dist-to-docs',
    apply: 'build',

    async writeBundle() {
      console.log('📁 Copying dist to docs...');

      const distDir = path.resolve(__dirname, 'dist');
      const docsDir = path.resolve(__dirname, 'docs');

      if (!fs.existsSync(distDir)) {
        console.log('❌ dist directory not found');
        return;
      }

      // Ждем завершения всех других плагинов
      await new Promise(resolve => setTimeout(resolve, 2000));

      if (fs.existsSync(docsDir)) {
        console.log('🗑️ Cleaning docs directory...');
        fs.rmSync(docsDir, { recursive: true });
      }
      fs.mkdirSync(docsDir, { recursive: true });

      // Простая рекурсивная функция копирования
      const copyRecursiveSync = (src, dest) => {
        if (!fs.existsSync(src)) return;
        
        const stats = fs.statSync(src);
        
        if (stats.isDirectory()) {
          if (!fs.existsSync(dest)) {
            fs.mkdirSync(dest, { recursive: true });
          }
          
          const items = fs.readdirSync(src);
          for (const item of items) {
            if (item === 'html') continue;
            copyRecursiveSync(path.join(src, item), path.join(dest, item));
          }
        } else {
          fs.copyFileSync(src, dest);
        }
      };

      // Копируем всё из dist в docs, кроме html папки
      copyRecursiveSync(distDir, docsDir);
      console.log('✅ Basic structure copied');

      // Обрабатываем HTML файлы отдельно
      const htmlDir = path.join(distDir, 'html');
      if (fs.existsSync(htmlDir)) {
        const htmlFiles = fs.readdirSync(htmlDir).filter(f => f.endsWith('.html'));
        for (const htmlFile of htmlFiles) {
          const srcPath = path.join(htmlDir, htmlFile);
          const destPath = path.join(docsDir, htmlFile);
          
          if (fs.existsSync(srcPath)) {
            fs.copyFileSync(srcPath, destPath);

            console.log(`🔧 Fixing HTML quotes in: ${htmlFile}`);
            
            // Читаем содержимое HTML файла
            let content = fs.readFileSync(destPath, 'utf8');
            
            // 1. Исправляем пути в HTML файлах
            content = content
              .replace(/(src|href|data-src|srcset)=["']\/(assets|images|files)\//g, '$1="./$2/')
              .replace(/(src|href|data-src|srcset)=["']\.\.\/(assets|images|files)\//g, '$1="./$2/')
              .replace(/(src|href|data-src|srcset)=["']\.(?!\.)\//g, '$1="./');

            // 2. Исправляем проблему с кавычками в picture тегах
            content = content.replace(
              /<picture>\s*<source\s+srcset=("|')([^"']+)("|')\s+type=("|')image\/webp("|')\s*>/gi,
              (match, quote1, srcset, quote2, quote3, quote4) => {
                return `<picture><source srcset="${srcset}" type="image/webp">`;
              }
            );

            // Второй проход: исправляем случай, когда кавычки вообще отсутствуют
            content = content.replace(
              /<picture>\s*<source\s+srcset=([^\s>]+)\s+type=([^\s>]+)\s*>/gi,
              (match, srcset, type) => {
                const fixedSrcset = srcset.includes('"') ? srcset : `"${srcset}"`;
                const fixedType = type.includes('"') ? type : `"${type}"`;
                return `<picture><source srcset=${fixedSrcset} type=${fixedType}>`;
              }
            );

            // 3. Исправляем проблему с mixed quotes в img тегах
            content = content.replace(
              /<img([^>]*?)src=("|')([^"']+)("|')([^>]*?)>/gi,
              (match, before, quote1, src, quote2, after) => {
                let fixedAfter = after.replace(/(\w+)=("|')([^"']+)("|')/g, '$1="$3"');
                return `<img${before}src="${src}"${fixedAfter}>`;
              }
            );

            // 4. Дополнительное исправление для атрибутов alt, loading и class
            content = content.replace(
              /<img([^>]*?)alt=("|')([^"']*)("|')([^>]*?)>/gi,
              (match, before, quote1, alt, quote2, after) => {
                return `<img${before}alt="${alt}"${after}>`;
              }
            );

            content = content.replace(
              /<img([^>]*?)loading=("|')([^"']*)("|')([^>]*?)>/gi,
              (match, before, quote1, loading, quote2, after) => {
                return `<img${before}loading="${loading}"${after}>`;
              }
            );

            content = content.replace(
              /<img([^>]*?)class=("|')([^"']*)("|')([^>]*?)>/gi,
              (match, before, quote1, className, quote2, after) => {
                return `<img${before}class="${className}"${after}>`;
              }
            );

            // 5. Исправляем конкретную проблему из примера
            content = content.replace(
              /<picture><source srcset=("|')([^"']+)("|') type=("|')image\/webp("|')><img([^>]*?)src=("|')([^"']+)("|')([^>]*?)><\/picture>/gi,
              (match, quote1, webpSrc, quote2, quote3, quote4, imgAttrs, quote5, imgSrc, quote6, imgAfter) => {
                return `<picture><source srcset="${webpSrc}" type="image/webp"><img${imgAttrs}src="${imgSrc}"${imgAfter}></picture>`;
              }
            );

            // 6. Общее исправление для всех тегов с атрибутами
            content = content.replace(
              /<(\w+)([^>]*?)>/gi,
              (match, tagName, attributes) => {
                if (tagName.toLowerCase() === 'script' || tagName.toLowerCase() === 'style') {
                  return match;
                }
                
                const fixedAttributes = attributes.replace(
                  /(\w+)=("|')([^"']*)("|')/g,
                  '$1="$3"'
                );
                
                return `<${tagName}${fixedAttributes}>`;
              }
            );

            // Записываем исправленное содержимое
            fs.writeFileSync(destPath, content, 'utf8');
            console.log(`✅ Fixed HTML quotes in: ${htmlFile}`);
          }
        }
        console.log(`✅ Copied and fixed ${htmlFiles.length} HTML files to docs root`);
      }

      console.log('✅ dist successfully copied to docs with HTML fixes');
      
      // Детальная проверка содержимого
      console.log('📁 Final docs structure:');
      if (fs.existsSync(docsDir)) {
        const items = fs.readdirSync(docsDir);
        console.log('📋 Docs contents:', items);
        
        const imagesDir = path.join(docsDir, 'images');
        if (fs.existsSync(imagesDir)) {
          const images = fs.readdirSync(imagesDir);
          console.log('🖼️ Images in docs:', images.length, 'files');
        }
      }
    }
  };
};

// Плагин для автоматического подключения шрифтов
const fontAutoPlugin = () => {
  let lastFontHash = null;

  const getFontDirHash = (fontsDir) => {
    try {
      const files = fs.readdirSync(fontsDir)
        .filter(file => /\.(woff2|woff|ttf|otf)$/i.test(file))
        .sort()
        .map(file => `${file}-${fs.statSync(path.join(fontsDir, file)).mtimeMs}`)
        .join('|');
      return files ? require('crypto').createHash('md5').update(files).digest('hex') : null;
    } catch {
      return null;
    }
  };

  return {
    name: 'font-auto-plugin',

    async buildStart() {
      const fontsDir = path.resolve(__dirname, 'src/files/fonts');
      const cssOutputDir = path.resolve(__dirname, 'src/scss/main');
      const cssFilePath = path.join(cssOutputDir, 'fonts.scss');

      if (!fs.existsSync(fontsDir)) {
        console.log('Fonts directory not found, skipping font generation');
        return;
      }

      if (!fs.existsSync(cssOutputDir)) {
        fs.mkdirSync(cssOutputDir, { recursive: true });
      }

      const currentHash = getFontDirHash(fontsDir);

      if (lastFontHash === currentHash && fs.existsSync(cssFilePath)) {
        console.log('✅ fonts.scss is up to date, skipping regeneration');
        return;
      }

      console.log('🔄 Fonts changed or first run — regenerating fonts.scss');

      try {
        const fontFiles = fs.readdirSync(fontsDir);
        const fontFaceRules = [];
        const fontFamilies = {};

        for (const file of fontFiles) {
          if (/\.(woff2|woff|ttf|otf)$/i.test(file)) {
            const fileName = path.parse(file).name;
            const ext = path.parse(file).ext.slice(1);

            const match = fileName.match(/(.*?)([-_](bold|italic|light|medium|regular|black|extrabold|semibold|thin|extralight))?$/i);
            const familyName = match ? match[1].replace(/[-_]/g, ' ') : fileName;
            const style = match && match[3] ? match[3] : 'regular';

            if (!fontFamilies[familyName]) {
              fontFamilies[familyName] = [];
            }

            fontFamilies[familyName].push({
              file,
              ext,
              style: style.toLowerCase(),
              weight: getFontWeight(style),
              isItalic: style.toLowerCase().includes('italic')
            });
          }
        }

        for (const [family, variants] of Object.entries(fontFamilies)) {
          for (const variant of variants) {
            const fontFaceRule = `
@font-face {
  font-family: '${family}';
  src: url('../../files/fonts/${variant.file}') format('${getFormat(variant.ext)}');
  font-weight: ${variant.weight};
  font-style: ${variant.isItalic ? 'italic' : 'normal'};
  font-display: swap;
}
            `.trim();
            fontFaceRules.push(fontFaceRule);
          }
        }

        if (fontFaceRules.length > 0) {
          const cssContent = `/* Auto-generated font styles */\n${fontFaceRules.join('\n\n')}`;
          fs.writeFileSync(cssFilePath, cssContent);
          console.log(`✅ Generated fonts.scss with ${fontFaceRules.length} @font-face rules`);
          lastFontHash = currentHash;
        } else {
          console.log('❌ No font face rules were generated');
        }

      } catch (error) {
        console.error('Error generating font styles:', error);
      }
    }
  };
};

// Кастомный плагин для замены алиасов в HTML
const aliasHtmlPlugin = () => {
  return {
    name: 'alias-html',
    transformIndexHtml(html) {
      const aliasMap = {
        '@img/': '/images/',
        '@scss/': './scss/',
        '@js/': './js/',
        '@bg/': './img/',
        '@fonts/': './fonts/'
      };
      
      let transformedHtml = html;
      for (const [alias, realPath] of Object.entries(aliasMap)) {
        transformedHtml = transformedHtml.replace(new RegExp(alias, 'g'), realPath);
      }
      
      return transformedHtml;
    },
  };
};

// ИСПРАВЛЕННЫЙ плагин для работы с изображениями
const imagesPlugin = () => {
  let isBuild = false;

  return {
    name: 'images-plugin',

    config(config, { command }) {
      isBuild = command === 'build';
    },

    // Используем generateBundle вместо buildStart
    async generateBundle() {
      if (!isBuild) return;

      console.log('🖼️ Processing images...');
      
      const imagesSrcDir = path.resolve(__dirname, 'src/images');
      const imagesDistDir = path.resolve(__dirname, 'dist/images');
      const webpDistDir = path.join(imagesDistDir, 'webp');

      if (!fs.existsSync(imagesSrcDir)) {
        console.log('📁 Images directory not found, skipping image processing');
        return;
      }

      // Создаем папки назначения
      if (!fs.existsSync(imagesDistDir)) {
        fs.mkdirSync(imagesDistDir, { recursive: true });
      }
      if (!fs.existsSync(webpDistDir)) {
        fs.mkdirSync(webpDistDir, { recursive: true });
      }

      try {
        const files = fs.readdirSync(imagesSrcDir);
        let copiedCount = 0;
        let webpCount = 0;

        for (const file of files) {
          const srcPath = path.join(imagesSrcDir, file);
          const distPath = path.join(imagesDistDir, file);

          // Копируем оригинальные изображения
          if (/\.(jpg|jpeg|png|gif|svg|ico)$/i.test(file)) {
            fs.copyFileSync(srcPath, distPath);
            copiedCount++;
            console.log(`📄 Copied: ${file}`);
          }

          // Генерируем WebP для подходящих форматов
          if (/\.(jpg|jpeg|png)$/i.test(file)) {
            const webpPath = path.join(webpDistDir, `${path.parse(file).name}.webp`);
            try {
              await sharp(srcPath)
                .webp({ quality: 80, effort: 4 })
                .toFile(webpPath);
              webpCount++;
              console.log(`🎨 Created WebP: ${path.parse(file).name}.webp`);
            } catch (error) {
              console.warn(`⚠️ Could not convert ${file} to WebP:`, error.message);
            }
          }
        }

        console.log(`✅ Copied ${copiedCount} original images`);
        console.log(`✅ Generated ${webpCount} WebP images`);
        
        // Проверяем результат
        if (fs.existsSync(imagesDistDir)) {
          const distImages = fs.readdirSync(imagesDistDir);
          console.log('📋 Images in dist:', distImages);
        }
        if (fs.existsSync(webpDistDir)) {
          const webpImages = fs.readdirSync(webpDistDir);
          console.log('🎨 WebP images generated:', webpImages.length);
        }
        
      } catch (error) {
        console.error('❌ Error processing images:', error);
      }
    }
  };
};

// Более надежный плагин для обработки изображений
const pictureWebpPlugin = () => {
  let isBuild = false;

  return {
    name: 'picture-webp-plugin',

    config(config, { command }) {
      isBuild = command === 'build';
    },
    
    transformIndexHtml(html) {
      if (!isBuild) {
        return html;
      }

      console.log('🖼️ Wrapping images in <picture> tags for production...');
      
      // Универсальное регулярное выражение для поиска img тегов
      const imgRegex = /<img\b([^>]*?\bsrc\s*=\s*(["'])([^"']+?\.(png|jpe?g|jpg))\2[^>]*?)>/gi;
      
      let result = html;
      let match;
      
      // Обрабатываем каждое совпадение отдельно для лучшего контроля
      while ((match = imgRegex.exec(html)) !== null) {
        const fullMatch = match[0];
        const attributes = match[1];
        const quote = match[2];
        const src = match[3];
        
        // Пропускаем изображения, которые уже в picture или имеют data-skip-webp
        if (fullMatch.includes('data-skip-webp') || 
            fullMatch.includes('<picture') || 
            html.substring(match.index - 50, match.index).includes('<picture')) {
          continue;
        }
        
        let webpSrc;
        
        if (src.startsWith('/images/')) {
          webpSrc = src.replace('/images/', '/images/webp/').replace(/\.(png|jpe?g|jpg)$/i, '.webp');
        } else if (src.startsWith('images/')) {
          webpSrc = src.replace('images/', 'images/webp/').replace(/\.(png|jpe?g|jpg)$/i, '.webp');
        } else if (src.startsWith('./images/')) {
          webpSrc = src.replace('./images/', './images/webp/').replace(/\.(png|jpe?g|jpg)$/i, '.webp');
        } else {
          const lastSlashIndex = src.lastIndexOf('/');
          if (lastSlashIndex !== -1) {
            const path = src.substring(0, lastSlashIndex);
            const fileName = src.substring(lastSlashIndex + 1);
            const webpFileName = fileName.replace(/\.(png|jpe?g|jpg)$/i, '.webp');
            webpSrc = `${path}/webp/${webpFileName}`;
          } else {
            webpSrc = src.replace(/\.(png|jpe?g|jpg)$/i, '.webp');
          }
        }
        
        // Используем тот же тип кавычек, что и в оригинальном теге
        const replacement = `<picture><source srcset=${quote}${webpSrc}${quote} type="image/webp">${fullMatch}</picture>`;
        result = result.replace(fullMatch, replacement);
      }
      
      return result;
    }
  };
};

export default defineConfig({
  root: path.resolve(__dirname, 'src'),
  base: './',

  resolve: {
    alias: {
      '@img': path.resolve(__dirname, 'src/images'),
      '@scss': path.resolve(__dirname, 'src/scss'),
      '@js': path.resolve(__dirname, 'src/js'),
      '@bg': path.resolve(__dirname, 'src/img'),
      '@fonts': path.resolve(__dirname, 'src/files/fonts'),
    },
  },

  plugins: [
    fontAutoPlugin(),
    handlebars({
      partialDirectory: path.resolve(__dirname, 'src/html/partials'),
      context: {
        title: {
          index: 'Главная',
        },
      },
    }),
    aliasHtmlPlugin(),
    imagesPlugin(),
    pictureWebpPlugin(),
    tailwindcss(),
    
    // ✅ ДОБАВЛЯЕМ CRITICAL CSS ПЛАГИН
    criticalCSSPlugin(),
    simpleAsyncCSSPlugin(),
    copyDistToDocs(),
  ],

  build: {
    rollupOptions: {
      input: rollupInputs,
      output: {
        manualChunks: {
          vendor: ['swiper', 'inputmask'],
        },
        assetFileNames: (assetInfo) => {
          if (assetInfo.name && /\.(woff|woff2|eot|ttf|otf)$/i.test(assetInfo.name)) {
            return `files/fonts/[name][extname]`;
          }
          if (assetInfo.name && /\.(jpg|jpeg|png|gif|svg|ico)$/i.test(assetInfo.name)) {
            return `images/[name][extname]`;
          }
          // Разделяем CSS файлы
          if (assetInfo.name && /\.css$/i.test(assetInfo.name)) {
            if (assetInfo.name.includes('critical')) {
              return `assets/critical-[name]-[hash][extname]`;
            }
            return `assets/[name]-[hash][extname]`;
          }
          return `assets/[name]-[hash][extname]`;
        },
        chunkFileNames: 'assets/[name]-[hash].js',
        entryFileNames: 'assets/[name]-[hash].js',
      },
    },
    
    chunkSizeWarningLimit: 1000,
    minify: true,
    sourcemap: false, // Отключаем для production
    outDir: path.resolve(__dirname, 'dist'),
    assetsInlineLimit: 4096, // Включаем инлайнинг мелких файлов
    emptyOutDir: true,
    
    // ✅ ОПТИМИЗАЦИЯ CSS
    cssCodeSplit: true,
    cssMinify: true,
  },

  server: {
    open: '/html/index.html',
    watch: {
      ignored: [
        '**/node_modules/**',
        '**/.git/**',
        '**/dist/**',
        '**/docs/**',
        '**/src/files/**',
        '**/src/images/webp/**',
      ],
    },
  },
});

// Экспортируем объект для возможного использования в других модулях
export { rollupInputs };