// Auto-generated from vite.config.js
// Generated on: 2025-10-04T11:56:44.044Z
// DO NOT EDIT THIS FILE MANUALLY

/**
 * Rollup input configuration for Vite build
 * Contains absolute paths to HTML entry points
 */
export const rollupInputs = {
  "Главная": "D:\\Проекты\\template\\template\\src\\html\\index.html",
  "ui_kit": "D:\\Проекты\\template\\template\\src\\html\\ui-kit.html",
  "error": "D:\\Проекты\\template\\template\\src\\html\\404.html"
};

/**
 * Relative paths from src directory
 * Useful for navigation within the project
 */
export const relativePaths = {
  "Главная": "html\\index.html",
  "ui_kit": "html\\ui-kit.html",
  "error": "html\\404.html"
};

/**
 * List of available page keys
 */
export const pageKeys = [
  "Главная",
  "ui_kit",
  "error"
];

/**
 * Get the path for a specific page
 * @param {string} pageKey - Key of the page (index, ui_kit, error, etc.)
 * @returns {string|null} Absolute path or null if not found
 */
export function getPagePath(pageKey) {
  return rollupInputs[pageKey] || null;
}

/**
 * Get the relative path for a specific page
 * @param {string} pageKey - Key of the page (index, ui_kit, error, etc.)
 * @returns {string|null} Relative path from src directory or null if not found
 */
export function getPageRelativePath(pageKey) {
  return relativePaths[pageKey] || null;
}

/**
 * Check if a page key exists
 * @param {string} pageKey - Key to check
 * @returns {boolean} True if the page exists
 */
export function hasPage(pageKey) {
  return pageKey in rollupInputs;
}

export default rollupInputs;
